// packages/vue-better-tweet/src/twitter-theme/embedded-tweet.vue
<script setup lang="ts">
import type { Tweet } from '../api/index.js'
import type { TwitterComponents } from './types'
import { computed } from 'vue'
import TweetContainer from './tweet-container.vue'
import TweetHeader from './tweet-header.vue'
import TweetInReplyTo from './tweet-in-reply-to.vue'
import TweetBody from './tweet-body.vue'
import TweetMedia from './tweet-media.vue'
import TweetInfo from './tweet-info.vue'
import TweetActions from './tweet-actions.vue'
import TweetReplies from './tweet-replies.vue'
import { QuotedTweet } from './quoted-tweet/index.js'
import { enrichTweet } from '../utils.js'

type Props = {
  tweet: Tweet
  components?: Omit<TwitterComponents, 'TweetNotFound'>
}

const props = defineProps<Props>()
const enrichedTweet = computed(() => enrichTweet(props.tweet))
</script>

<template>
  <TweetContainer>
    <TweetHeader :tweet="enrichedTweet" :components="props.components" />
    <TweetInReplyTo
      v-if="enrichedTweet.in_reply_to_status_id_str"
      :tweet="enrichedTweet"
    />
    <TweetBody :tweet="enrichedTweet" />
    <TweetMedia
      v-if="enrichedTweet.mediaDetails?.length"
      :tweet="enrichedTweet"
      :components="props.components"
    />
    <QuotedTweet
      v-if="enrichedTweet.quoted_tweet"
      :tweet="enrichedTweet.quoted_tweet"
      :components="props.components"
    />
    <TweetInfo :tweet="enrichedTweet" />
    <TweetActions :tweet="enrichedTweet" />
    <TweetReplies :tweet="enrichedTweet" />
  </TweetContainer>
</template>

// packages/react-tweet/src/twitter-theme/embedded-tweet.tsx
import type { Tweet } from '../api/index.js'
import type { TwitterComponents } from './types.jsx'
import { TweetContainer } from './tweet-container.jsx'
import { TweetHeader } from './tweet-header.jsx'
import { TweetInReplyTo } from './tweet-in-reply-to.jsx'
import { TweetBody } from './tweet-body.jsx'
import { TweetMedia } from './tweet-media.jsx'
import { TweetInfo } from './tweet-info.jsx'
import { TweetActions } from './tweet-actions.jsx'
import { TweetReplies } from './tweet-replies.jsx'
import { QuotedTweet } from './quoted-tweet/index.js'
import { enrichTweet } from '../utils.js'
import { useMemo } from 'react'

type Props = {
  tweet: Tweet
  components?: Omit<TwitterComponents, 'TweetNotFound'>
}

export const EmbeddedTweet = ({ tweet: t, components }: Props) => {
  // useMemo does nothing for RSC but it helps when the component is used in the client (e.g by SWR)
  const tweet = useMemo(() => enrichTweet(t), [t])
  return (
    <TweetContainer>
      <TweetHeader tweet={tweet} components={components} />
      {tweet.in_reply_to_status_id_str && <TweetInReplyTo tweet={tweet} />}
      <TweetBody tweet={tweet} />
      {tweet.mediaDetails?.length ? (
        <TweetMedia tweet={tweet} components={components} />
      ) : null}
      {tweet.quoted_tweet && <QuotedTweet tweet={tweet.quoted_tweet} components={components} />}
      <TweetInfo tweet={tweet} />
      <TweetActions tweet={tweet} />
      <TweetReplies tweet={tweet} />
    </TweetContainer>
  )
}
